# Generated by Django 3.2.8 on 2021-11-26 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('unit_type', models.CharField(choices=[('teaspoon', 'Colher de Chá'), ('tablespoon', 'Colher de Sopa'), ('cup', 'Xícara'), ('milliliter', 'ml'), ('liter', 'l'), ('milligram', 'mg'), ('gram', 'g'), ('kilogram', 'kg'), ('millimeter', 'mm'), ('centimeter', 'cm'), ('meter', 'm'), ('to_taste', 'A gosto')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Eggs, milk and milk products', 'Ovos, leites e derivados de leite'), ('Fats and oils', 'Gorduras e óleos'), ('Fruits', 'Frutas'), ('Grain, nuts and baking products', 'Cereais, nozes e produtos de panificação'), ('Herbs and spices', 'Ervas e especiarias'), ('Meat, sausages and fish', 'Carnes, linguiças e peixes'), ('Pasta, rice and pulses', 'Macarrão, arroz e leguminosas'), ('Vegetables', 'Legumes'), ('Others', 'Outros')], max_length=255, null=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='api.recipe')),
            ],
        ),
    ]
